"""empty message

Revision ID: bc0427ecfc88
Revises: edeb861c6cbf
Create Date: 2025-07-18 17:57:03.266766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc0427ecfc88'
down_revision = 'edeb861c6cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('client', 'professional', name='role'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
