"""empty message

Revision ID: bfd7f3a0df67
Revises: bc0427ecfc88
Create Date: 2025-07-18 17:57:26.848606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd7f3a0df67'
down_revision = 'bc0427ecfc88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('client', 'professional', name='role'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
