"""empty message

Revision ID: d2992cec5770
Revises: 6a92735b6e1f
Create Date: 2025-07-18 18:05:11.777709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2992cec5770'
down_revision = '6a92735b6e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('client', 'professional', name='role'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
