"""empty message

Revision ID: f237cf7aaad8
Revises: 0e50c8d20752
Create Date: 2025-06-16 18:57:30.173101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f237cf7aaad8'
down_revision = '0e50c8d20752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('video', sa.String(length=255), nullable=True))
        batch_op.alter_column('rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', postgresql.ENUM('image', 'video', name='media'), autoincrement=False, nullable=True))
        batch_op.alter_column('rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('video')
        batch_op.drop_column('img')

    # ### end Alembic commands ###
